# Generated by Django 4.2.13 on 2026-03-01 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sentiment_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("input_type", models.CharField(choices=[("single", "Kalimat"), ("file", "CSV/TXT")], max_length=12)),
                ("text_input", models.TextField(blank=True)),
                ("source_name", models.CharField(blank=True, max_length=255)),
                ("text_column", models.CharField(blank=True, max_length=100)),
                ("sample_count", models.PositiveIntegerField(default=1)),
                ("columns", models.JSONField(blank=True, default=list)),
                ("rows", models.JSONField(blank=True, default=list)),
                ("output_filename", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prediction_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
