# Generated by Django 4.2.13 on 2026-03-02 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sentiment_app", "0002_predictionhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapeTempChunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("chunk_index", models.PositiveIntegerField(default=0)),
                ("rows", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temp_chunks",
                        to="sentiment_app.scrapehistory",
                    ),
                ),
            ],
            options={
                "ordering": ["chunk_index", "id"],
            },
        ),
    ]
