# Generated by Django 4.2.13 on 2026-03-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sentiment_app", "0003_scrapetempchunk"),
    ]

    operations = [
        migrations.AddField(
            model_name="scrapehistory",
            name="is_complete",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="scrapehistory",
            name="resume_next_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scrapehistory",
            name="stop_reason",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="scrapehistory",
            name="window_days",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
